@extends('layouts.app')
@section('title','Payroll Record — '.$payroll->employee?->first_name.' '.$payroll->employee?->last_name)
@section('content')
<div class="animate-in">
  <div style="display:flex;align-items:center;gap:12px;margin-bottom:20px;flex-wrap:wrap">
    <a href="{{ route('hris.workflow.financial_payroll_information') }}" class="btn btn-secondary btn-sm">← Back</a>
    <div class="section-title" style="margin:0">Payroll Record #{{ $payroll->id }}</div>
    <span class="badge {{ $payroll->status === 'finalized' ? 'badge-offer-accepted' : 'badge-pending' }}" style="text-transform:capitalize">{{ $payroll->status }}</span>
  </div>

  <div class="card-section" style="max-width:680px">
    <div style="display:grid;grid-template-columns:1fr 1fr;gap:14px;font-size:13px;margin-bottom:20px">
      <div><span style="color:var(--text3)">Employee</span><br><strong>{{ $payroll->employee?->first_name }} {{ $payroll->employee?->last_name }}</strong></div>
      <div><span style="color:var(--text3)">Role</span><br>{{ $payroll->employee?->role ?? '—' }}</div>
      <div><span style="color:var(--text3)">Period</span><br>{{ $payroll->period_start->format('M j, Y') }} – {{ $payroll->period_end->format('M j, Y') }}</div>
      <div><span style="color:var(--text3)">Frequency</span><br>{{ ucwords(str_replace('_', '-', $payroll->frequency)) }}</div>
      <div><span style="color:var(--text3)">Pay Date</span><br>{{ $payroll->pay_date ? $payroll->pay_date->format('M j, Y') : '—' }}</div>
      <div><span style="color:var(--text3)">Generated By</span><br>{{ $payroll->generatedBy?->first_name }} {{ $payroll->generatedBy?->last_name ?? '—' }}</div>
    </div>

    <table style="width:100%;border-collapse:collapse;font-size:13px">
      <thead>
        <tr><th style="text-align:left;padding:8px 10px;background:var(--bg2);border-radius:6px 0 0 6px">Item</th><th style="text-align:right;padding:8px 10px;background:var(--bg2)">Hours</th><th style="text-align:right;padding:8px 10px;background:var(--bg2);border-radius:0 6px 6px 0">Amount</th></tr>
      </thead>
      <tbody>
        <tr><td style="padding:8px 10px;border-bottom:1px solid var(--border)">Regular Pay ({{ $payroll->pay_type }} @ ${{ number_format($payroll->employee_rate, 2) }})</td><td style="padding:8px 10px;border-bottom:1px solid var(--border);text-align:right">{{ $payroll->pay_type === 'hourly' ? number_format($payroll->regular_hours, 2) : '—' }}</td><td style="padding:8px 10px;border-bottom:1px solid var(--border);text-align:right">${{ number_format($payroll->regular_pay, 2) }}</td></tr>
        @if($payroll->overtime_pay > 0)
        <tr><td style="padding:8px 10px;border-bottom:1px solid var(--border)">Overtime ({{ number_format($payroll->overtime_hours, 2) }} hrs × 1.5)</td><td style="padding:8px 10px;border-bottom:1px solid var(--border);text-align:right">{{ number_format($payroll->overtime_hours, 2) }}</td><td style="padding:8px 10px;border-bottom:1px solid var(--border);text-align:right">${{ number_format($payroll->overtime_pay, 2) }}</td></tr>
        @endif
        @if($payroll->bonus > 0)
        <tr><td style="padding:8px 10px;border-bottom:1px solid var(--border)">Bonus / Other</td><td style="padding:8px 10px;border-bottom:1px solid var(--border);text-align:right">—</td><td style="padding:8px 10px;border-bottom:1px solid var(--border);text-align:right">${{ number_format($payroll->bonus, 2) }}</td></tr>
        @endif
        <tr><td style="padding:8px 10px;font-weight:700">Gross Pay</td><td></td><td style="padding:8px 10px;text-align:right;font-weight:700">${{ number_format($payroll->gross_pay, 2) }}</td></tr>
        @if($payroll->deductions > 0)
        <tr><td style="padding:8px 10px;color:var(--red)">Deductions</td><td></td><td style="padding:8px 10px;text-align:right;color:var(--red)">−${{ number_format($payroll->deductions, 2) }}</td></tr>
        @endif
        <tr style="background:var(--bg2)"><td style="padding:10px;font-size:15px;font-weight:700;border-radius:6px 0 0 6px">Net Pay</td><td></td><td style="padding:10px;text-align:right;font-size:15px;font-weight:700;color:var(--green);border-radius:0 6px 6px 0">${{ number_format($payroll->net_pay, 2) }}</td></tr>
      </tbody>
    </table>

    @if($payroll->notes)
    <div style="margin-top:16px;font-size:13px;color:var(--text2)"><strong>Notes:</strong> {{ $payroll->notes }}</div>
    @endif

    <div style="display:flex;gap:10px;flex-wrap:wrap;margin-top:20px">
      <button class="btn btn-warning btn-sm" onclick="openEditPayrollRecord()">✏ Edit</button>
      <a href="{{ route('hris.payrolls.pdf', $payroll) }}" class="btn btn-secondary btn-sm" target="_blank">📥 Download PDF</a>
      <button class="btn btn-danger btn-sm" onclick="deletePayrollRecord()">Delete</button>
    </div>
  </div>
</div>

<!-- Edit modal -->
<div class="modal-overlay" id="modal-editPayrollRecord" onclick="if(event.target===this)closeModal('editPayrollRecord')">
  <div class="modal" style="max-width:540px">
    <div class="modal-header"><h3>Edit Payroll Record</h3><button onclick="closeModal('editPayrollRecord')">✕</button></div>
    <div class="modal-body">
      <div class="form-row">
        <div class="form-group"><label>Pay Frequency</label>
          <select id="epFreq">
            <option value="weekly">Weekly</option>
            <option value="biweekly" selected>Bi-Weekly</option>
            <option value="semi_monthly">Semi-Monthly</option>
            <option value="monthly">Monthly</option>
          </select>
        </div>
        <div class="form-group"><label>Status</label>
          <select id="epStatus">
            <option value="draft">Draft</option>
            <option value="finalized">Finalized</option>
          </select>
        </div>
      </div>
      <div class="form-row">
        <div class="form-group"><label>Period Start</label><input type="date" id="epStart"></div>
        <div class="form-group"><label>Period End</label><input type="date" id="epEnd"></div>
      </div>
      <div class="form-group"><label>Pay Date</label><input type="date" id="epPayDate"></div>
      <div class="form-row">
        <div class="form-group"><label>Regular Hours</label><input type="number" id="epRegHours" step="0.01" min="0"></div>
        <div class="form-group"><label>Overtime Hours</label><input type="number" id="epOtHours" step="0.01" min="0"></div>
      </div>
      <div class="form-row">
        <div class="form-group"><label>Bonus ($)</label><input type="number" id="epBonus" step="0.01" min="0"></div>
        <div class="form-group"><label>Deductions ($)</label><input type="number" id="epDeductions" step="0.01" min="0"></div>
      </div>
      <div class="form-group"><label>Notes</label><textarea id="epNotes" rows="3"></textarea></div>
    </div>
    <div class="modal-footer">
      <button class="btn btn-secondary" onclick="closeModal('editPayrollRecord')">Cancel</button>
      <button class="btn btn-primary" onclick="savePayrollEdit()">Save Changes</button>
    </div>
  </div>
</div>
@endsection

@push('scripts')
<script>
var _pr = {
  id: {{ $payroll->id }},
  employee_id: {{ $payroll->employee_id }},
  frequency: '{{ $payroll->frequency }}',
  status: '{{ $payroll->status }}',
  period_start: '{{ $payroll->period_start->format('Y-m-d') }}',
  period_end: '{{ $payroll->period_end->format('Y-m-d') }}',
  pay_date: '{{ $payroll->pay_date?->format('Y-m-d') ?? '' }}',
  regular_hours: {{ $payroll->regular_hours }},
  overtime_hours: {{ $payroll->overtime_hours }},
  bonus: {{ $payroll->bonus }},
  deductions: {{ $payroll->deductions }},
  notes: '{{ addslashes($payroll->notes ?? '') }}'
};

function openEditPayrollRecord(){
  document.getElementById('epFreq').value = _pr.frequency;
  document.getElementById('epStatus').value = _pr.status;
  document.getElementById('epStart').value = _pr.period_start;
  document.getElementById('epEnd').value = _pr.period_end;
  document.getElementById('epPayDate').value = _pr.pay_date;
  document.getElementById('epRegHours').value = _pr.regular_hours;
  document.getElementById('epOtHours').value = _pr.overtime_hours;
  document.getElementById('epBonus').value = _pr.bonus;
  document.getElementById('epDeductions').value = _pr.deductions;
  document.getElementById('epNotes').value = _pr.notes;
  openModal('editPayrollRecord');
}

async function savePayrollEdit(){
  var body = {
    employee_id: _pr.employee_id,
    frequency: document.getElementById('epFreq').value,
    status: document.getElementById('epStatus').value,
    period_start: document.getElementById('epStart').value,
    period_end: document.getElementById('epEnd').value,
    pay_date: document.getElementById('epPayDate').value || null,
    regular_hours: parseFloat(document.getElementById('epRegHours').value) || 0,
    overtime_hours: parseFloat(document.getElementById('epOtHours').value) || 0,
    bonus: parseFloat(document.getElementById('epBonus').value) || 0,
    deductions: parseFloat(document.getElementById('epDeductions').value) || 0,
    notes: document.getElementById('epNotes').value,
  };
  var r = await apiFetch('/api/payrolls/'+_pr.id, {method:'PATCH', body:JSON.stringify(body)});
  if(!r||!r.ok){var e=r?await r.json():{};toast(e.message||'Update failed','error');return;}
  toast('Payroll record updated!','success');
  closeModal('editPayrollRecord');
  window.location.reload();
}

async function deletePayrollRecord(){
  if(!confirm('Delete this payroll record? This cannot be undone.')) return;
  var r = await apiFetch('/api/payrolls/'+_pr.id, {method:'DELETE'});
  if(!r||!r.ok){toast('Delete failed','error');return;}
  toast('Deleted.','success');
  window.location.href = '{{ route('hris.workflow.financial_payroll_information') }}';
}
</script>
@endpush
